pipeline {
    agent any
    stages{
        stage("Clean Up") {
            steps {
                echo "deleting project directory"
                deleteDir()
            }
        }
        stage("Checkout") {
            steps {
                echo "checkout the branch"
                sh "git clone https://github.com/17140095/SpringJenkinsDemo.git"
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
        }
    }
}