pipeline {
    agent any
    stages{

        stage("Build") {
            steps {
                dir("SpringJenkinsDemo") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("SpringJenkinsDemo") {
                    sh "mvn test"
                }
            }
        }
        stage("Completed") {
            steps {
                echo "Successfully Completed deployment!"
            }
        }
    }
}